# Generated by Django 5.0.6 on 2024-06-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('organized', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.area')),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('field', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('parking', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.area')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.constructionorganization')),
            ],
        ),
    ]
